version: '3.8'

x-rcl-service: &rcl-service
  cpus: 1.50
  mem_limit: 1536m

x-dls-service: &dls-service
  cpus: 1.00
  mem_limit: 1536m

x-neighborhood-service: &neighborhood-service
  cpus: 0.75
  mem_limit: 768m

x-postgres-service: &postgres-service
  cpus: 0.50
  mem_limit: 512m

services:
  grasp-fs-rcl-su:
    <<: *rcl-service
    build:
      context: ./grasp-fs-rcl-generator/Features Selection/Symmetrical Uncertainty/grasp-fs-rcl-su
    environment:
      JAVA_OPTS: "-Xms256m -Xmx1024m -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
      SPRING_TASK_EXECUTION_POOL_CORE_SIZE: "2"
      SPRING_TASK_EXECUTION_POOL_MAX_SIZE: "4"
      SPRING_TASK_EXECUTION_POOL_QUEUE_CAPACITY: "80"
    ports:
      - "8087:8087"
    volumes:
      - dataset_volume:/datasets
      - metrics_volume:/metrics
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started
  grasp-fs-rcl-rf:
    <<: *rcl-service
    build:
      context: ./grasp-fs-rcl-generator/Features Selection/RelieF/grasp-fs-rcl-rf
    environment:
      JAVA_OPTS: "-Xms256m -Xmx1024m -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
      SPRING_TASK_EXECUTION_POOL_CORE_SIZE: "2"
      SPRING_TASK_EXECUTION_POOL_MAX_SIZE: "4"
      SPRING_TASK_EXECUTION_POOL_QUEUE_CAPACITY: "80"
    ports:
      - "8086:8086"
    volumes:
      - dataset_volume:/datasets
      - metrics_volume:/metrics
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started
  grasp-fs-rcl-ig:
    <<: *rcl-service
    build:
      context: ./grasp-fs-rcl-generator/Features Selection/InfoGain/grasp-fs-rcl-ig
    environment:
      JAVA_OPTS: "-Xms256m -Xmx1024m -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
      SPRING_TASK_EXECUTION_POOL_CORE_SIZE: "2"
      SPRING_TASK_EXECUTION_POOL_MAX_SIZE: "4"
      SPRING_TASK_EXECUTION_POOL_QUEUE_CAPACITY: "80"
    ports:
      - "8089:8089"
    volumes:
      - dataset_volume:/datasets
      - metrics_volume:/metrics
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started
  grasp-fs-rcl-gr:
    <<: *rcl-service
    build:
      context: ./grasp-fs-rcl-generator/Features Selection/GainRatio/grasp-fs-rcl-gr
    environment:
      JAVA_OPTS: "-Xms256m -Xmx1024m -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
      SPRING_TASK_EXECUTION_POOL_CORE_SIZE: "2"
      SPRING_TASK_EXECUTION_POOL_MAX_SIZE: "4"
      SPRING_TASK_EXECUTION_POOL_QUEUE_CAPACITY: "80"
    ports:
      - "8088:8088"
    volumes:
      - dataset_volume:/datasets
      - metrics_volume:/metrics
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started
  grasp-fs.dls.verify:
    <<: *neighborhood-service
    build:
      context: ./grasp-fs-distributed-ls/Verify/grasp-fs.dls.verify
    environment:
      JAVA_OPTS: "-Xms128m -Xmx512m -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
      KAFKA_LISTENER_CONCURRENCY: "1"
    ports:
      - "8085:8085"
    volumes:
      - dataset_volume:/datasets
      - metrics_volume:/metrics
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started
  grasp-fs-dls-bf:
    <<: *dls-service
    build:
      context: ./grasp-fs-distributed-ls/Local Search/BitFlip/grasp-fs-dls-bf
    environment:
      JAVA_OPTS: "-Xms256m -Xmx1024m -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
      KAFKA_LISTENER_CONCURRENCY: "1"
    ports:
      - "8082:8082"
    volumes:
      - dataset_volume:/datasets
      - metrics_volume:/metrics
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started
  grasp-fs-dls-iw:
    <<: *dls-service
    build:
      context: ./grasp-fs-distributed-ls/Local Search/IWSS/grasp-fs-dls-iw
    environment:
      JAVA_OPTS: "-Xms256m -Xmx1024m -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
      KAFKA_LISTENER_CONCURRENCY: "1"
    ports:
      - "8083:8083"
    volumes:
      - dataset_volume:/datasets
      - metrics_volume:/metrics
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started
  grasp-fs-dls-iwr:
    <<: *dls-service
    build:
      context: ./grasp-fs-distributed-ls/Local Search/IWSSR/grasp-fs-dls-iwr
    environment:
      JAVA_OPTS: "-Xms256m -Xmx1024m -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
      KAFKA_LISTENER_CONCURRENCY: "1"
    ports:
      - "8084:8084"
    volumes:
      - dataset_volume:/datasets
      - metrics_volume:/metrics
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started
  grasp-fs-dls-rvnd:
    <<: *neighborhood-service
    build:
      context: ./grasp-fs-distributed-ls/Neighborhood/RVND/grasp-fs-dls-rvnd
    environment:
      JAVA_OPTS: "-Xms128m -Xmx512m -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
      KAFKA_LISTENER_CONCURRENCY: "1"
    ports:
      - "8090:8090"
    volumes:
      - dataset_volume:/datasets
      - metrics_volume:/metrics
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started
  grasp-fs-dls-vnd:
    <<: *neighborhood-service
    build:
      context: ./grasp-fs-distributed-ls/Neighborhood/VND/grasp-fs-dls-vnd
    environment:
      JAVA_OPTS: "-Xms128m -Xmx512m -XX:+UseContainerSupport -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Djava.security.egd=file:/dev/./urandom"
      KAFKA_LISTENER_CONCURRENCY: "1"
    ports:
      - "8091:8091"
    volumes:
      - dataset_volume:/datasets
      - metrics_volume:/metrics
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started
  zookeeper:
    cpus: 0.50
    mem_limit: 256m
    image: 'confluentinc/cp-zookeeper:7.4.0'
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    cpus: 1.00
    mem_limit: 1024m
    image: 'confluentinc/cp-kafka:7.4.0'
    ports:
      - '9092:9092'
      - '29092:29092'
      - '9999:9999'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL
      - KAFKA_NUM_PARTITIONS=6
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_JMX_PORT=9999
      - KAFKA_JMX_HOSTNAME=localhost
    depends_on:
      - zookeeper

  postgresql:
    <<: *postgres-service
    image: postgres:14
    hostname: postgresql
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "conduktor-console"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "change_me"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conduktor -d conduktor-console"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgresql-2:
    <<: *postgres-service
    image: postgres:14
    hostname: postgresql-sql
    volumes:
      - pg_data_sql:/var/lib/postgresql/data
    environment:
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_DB: "conduktor-sql"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "change_me"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U conduktor -d conduktor-sql"]
      interval: 10s
      timeout: 5s
      retries: 5

  conduktor-console:
    cpus: 0.75
    mem_limit: 768m
    image: conduktor/conduktor-console:1.32.0
    ports:
      - "8080:8080"
    volumes:
      - conduktor_data:/var/conduktor
    environment:
      CDK_DATABASE_URL: "postgresql://conduktor:change_me@postgresql:5432/conduktor-console"
      CDK_KAFKASQL_DATABASE_URL: "postgresql://conduktor:change_me@postgresql-sql:5432/conduktor-sql"
      CDK_ORGANIZATION_NAME: "local-dev"
      CDK_CLUSTERS_0_ID: "local-kafka"
      CDK_CLUSTERS_0_NAME: "local-kafka"
      CDK_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
      CDK_CLUSTERS_0_COLOR: "#6A57C8"
      CDK_CLUSTERS_0_ICON: "kafka"
      CDK_MONITORING_CORTEX-URL: http://conduktor-monitoring:9009/
      CDK_MONITORING_ALERT-MANAGER-URL: http://conduktor-monitoring:9010/
      CDK_MONITORING_CALLBACK-URL: http://conduktor-console:8080/monitoring/api/
      CDK_MONITORING_NOTIFICATIONS-CALLBACK-URL: http://localhost:8080
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started

  conduktor-monitoring:
    cpus: 0.50
    mem_limit: 384m
    image: conduktor/conduktor-console-cortex:1.32.0
    environment:
      CDK_CONSOLE-URL: "http://conduktor-console:8080"
    depends_on:
      postgresql:
        condition: service_healthy
      postgresql-2:
        condition: service_healthy
      kafka:
        condition: service_started

volumes:
  pg_data: {}
  pg_data_sql: {}
  conduktor_data: {}
  dataset_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./datasets
  metrics_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./metrics
