spring.application.name=grasp-fs-dls-vns
logging.pattern.console={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}","level":"%p","service":"${spring.application.name}","thread":"%thread","logger":"%logger{36}","message":"%msg"}%n
