
# Server config
server.port=8088

#Kafka config
spring.kafka.bootstrap-servers = kafka:29092
spring.kafka.consumer.group-id=myGroup
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
app.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer =org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class =org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.producer.properties.spring.json.type.mapping=br.com.graspfsdlsvnd.dto.DataSolution,br.com.graspfs.ls.bf.dto.DataSolution

spring.main.lazy-initialization=true
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
spring.task.execution.pool.core-size=${SPRING_TASK_EXECUTION_POOL_CORE_SIZE:2}
spring.task.execution.pool.max-size=${SPRING_TASK_EXECUTION_POOL_MAX_SIZE:4}
spring.task.execution.pool.queue-capacity=${SPRING_TASK_EXECUTION_POOL_QUEUE_CAPACITY:100}
spring.task.execution.thread-name-prefix=gr-async-
spring.application.name=grasp-fs-rcl-gr
logging.pattern.console={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}","level":"%p","service":"${spring.application.name}","thread":"%thread","logger":"%logger{36}","message":"%msg"}%n
