services:
  g-fshield-postgres:
    cpus: 0.50
    mem_limit: 512m
    image: postgres:14
    container_name: g-fshield-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: g-fshield
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - g-fshield-webservice-api-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d g-fshield"]
      interval: 10s
      timeout: 5s
      retries: 10

  g-fshield-redis:
    cpus: 0.25
    mem_limit: 256m
    image: redis:7-alpine
    container_name: g-fshield-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes"]
    volumes:
      - g-fshield-webservice-api-redis-data:/data

volumes:
  g-fshield-webservice-api-pg-data:
  g-fshield-webservice-api-redis-data:
