#Server port config
server.port = 8085

#kafka config
spring.kafka.bootstrap-servers = kafka:29092
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:grasp-fs-dls-verify-group}
spring.kafka.consumer.auto-offset-reset=${KAFKA_AUTO_OFFSET_RESET:latest}
spring.main.allow-bean-definition-overriding=true

kafka.listener.concurrency=${KAFKA_LISTENER_CONCURRENCY:1}

# Timeout para a BestSolution
verify.timeout.seconds=10
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
spring.application.name=grasp-fs-dls-verify
logging.pattern.console={"timestamp":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}","level":"%p","service":"${spring.application.name}","thread":"%thread","logger":"%logger{36}","message":"%msg"}%n
